### ISSUE TITLE
Error running .Net application after upgrading .Net NuGet 3.0.91 to 3.0.97

### ISSUE THREAD

**Issue by jsmitch122** [ligershark/WebOptimizer.Sass#65]
In existing code with method WebOptimizer.IAssetPipeline.AddScssBundle(....  we now get the following error when running.

System.InvalidOperationException: JS engine is not registered.
   at Microsoft.Extensions.DependencyInjection.PipelineExtensions.CheckJsEngineRegistration()
   at Microsoft.Extensions.DependencyInjection.PipelineExtensions.AddScssBundle(IAssetPipeline pipeline, WebOptimizerScssOptions options, String route, String[] sourceFiles)

**Comment by s3YwCf2ZbfJG4SHAfjQMAjtsf** [comment]
Just curious, 3.0.91 didn't have this requirement, correct?   The .Net 6 application didn't need to specify a JS engine previously.

**Comment by Taritsyn** [comment]
Hello, Peter!

Previously, this library was tightly bound to the JavaScriptEngineSwitcher.V8 module. Now you independently determine which module to use (see the [“Making used JavaScript engine configurable”](https://github.com/ligershark/WebOptimizer.Sass/issues/57) issue).

**Comment by lastme2** [comment]
Maybe there should be a default JS engine included still, with the ability to replace it if desired? - just to avoid such upgrade exceptions; most would probably expect consistent behaviour during package upgrades.

**Comment by Taritsyn** [comment]
Default engine is an additional dependency, and not the most lightweight one. Nowadays it is better to avoid additional dependencies.

It is possible that in this case the major version should have been changed.
